language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: UaODkRYmmb4va2rRBFSJdyOlgeDQ+8N/X60ovtq6lwJ+kw578YkLBPauqTGjq/urBpwLZPso2VhFxTNv9CAQQUAO5i8F/qPEXeCkfJPv3jWJ9fblnZZM43BspfBbv+oPI/fkEvUz8FLhIdhVQ98hitVZvPx5upFPE98Y0hxEKmYZRSzaEpY2WvjqXyhnrEy5U55Bg82cVfqdCVLC6v0W2KRajkPhcss3wkauP6rthRfZL7jOwuTd6SCEAeWNdFS2AK4DyirAN2xXnzVMzomeLL19UzDZ8EwRN2S8heQyIV1mEc3eOjsJ8bRdoVgMhwy+rxue53bUYgCfbM3Bhuo096QmEB51eocbbe+J9PwRcuMFSMdiHomHkZGomzQ3aCL53yEh7Myysb20kc0QUQd47pAlD0fM9zsOfMHlgGaCG4gcF7/r5LcSA4xDQjIrqsvpdafA7SixX1VWDdhhrsW7vsTjgudfSGD1obnmemtIHnyE1JjqdIaD1uVjqiCyXFnSboHLQfQWkF+r5Bzs02JLw0uUBe2Tr/myn0CkxFkjUrjtS0wLJptPtNu8jWQYmc4ZwtOUO5vM43WnZEulD3bi2/FFU2zKkdlNZsYgF5M/5FqDSCABYsEWHJLfutSsTHvK1qkY6+GPx5Ev0emV88+/yDQfq8rYde1yS2PoeeevWP0=
    - secure: gfDFe86jhEWCa3oRi48najf6MrRh8ZIfF22S82nnqm7jwxIV1JbHoyHXPUIgJSgLjYthKhr8u6GvY3xylVtR6ROef3a04T9sJeX/0fvLSqg5Y6aQtBTmsLZZmM8kGNLg1vtY+z+pJ9W6/XTo7gNM7ihZbmkkToj4EIVPapx5cuu2Ky0f2yMNMoT7fS+G6AB8qrkxPklFeZWwe4K7cZXmvjA6Tu2XoLRro9mRUQe+P11CFD3oqvIik6MHfaM2dRU+gSrlnQ6+L5GIqmiKhnX0B2RTDU5h6Pg488wTce6TztHj6j7OtYtMCBUSoGQWbD1HiiDZWAlRPkpCiNzOH8GkkvtHnRqww2Q6Ur/+S8zlioxyGoOBkCbRruWyS2KoFvjUlgucMnpaa5T3upk8qiStuBY6EkMf2k1SQE761WlRyflKpBKnRVnmspUhU604OsZLCLb1B1V6sBwZTNXsLk2bbH366micFUVmpvoWJr7BBK9SKpkZRFb2DIDbNWmYcGTWlFpHQnj5mEzV8VklkyGUPasmSYuJ115eIg9gV4HU4VwTIZ2/4LRgUrBBQVjaAcw+Oj7jhQLR+SMyw8GGQrWopWxaFV6KUoP3dxfXbIqc5PNby4RS3hAfPV0Ll+Sh8zcFbZORgZpsPH3Dqe33dnbH4N00rGzxAlf+pw4uogMs8xQ=
