language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
  - secure: ZM7uV2KaxNKSWTQ0HwZ3HfDtBmZFgR8hUwLQWtzk8y5/DOSlBx8HcCvm8NWCjPA27QJdnKt8TbIGmDOrabekliK2gL3oThwbexAdC90TfJUINTTJXjKDpJSTRr2o5UVu1wNv+1HRH/RUHLvlRHg5OMXaCeZdJCqe/RMFNo0PZF4nqlpIu1bD4wJ/qffwOhGUIwIGDFrm/BqyG7fw7VY8/AFfDNjz7bLEpTj0trRE46vbhgSpvoU/YXaeF2mFDNgXj4NRbQqwYMK754C3BD5jhBm50kGJ3R48D6Jl5hz4hLN/60B1YSs1hs0YWIC0S1bLf+M2MTWLsUUXcpvBZI3Jk/VS3xjhX7L/HDCH+x+nso5c+ob7vRmcQbmi6J0Ohhk960s6ukzF1CoZYtWF/RYxq/B1ExQtVPecg5RMzSlCPKq2v4xlyfU1UM2lXgVNjK4hErH/6lGy7aEJfwTk/poSxgWutgBQt7DjDHj7hbJKFEPU2IlmStuRAgbasCPbmU0cBzPJvztfd322KeduSe1v+13oXAljK/AUsFAhc2Qmc+V7oCR6yWJXOpEZf2zdMEjd7envOs0PCodAHZHtFwsrIvgMDbjFMNsOrljWXQdDKqkIh3Lldrx+XC01HjyOXdMPNuxhZnpAk1zBVH8YnEvsqSgPcL5LfyOsjz1cN1N8Rsw=
  - secure: Eoxd1Ikb7GQtPFWyTNebPSBGBkn8WUFRNNSy+yRCc2db5fPsbqsORlbmIHeQwVJxw32geFOUNoAYZZrY8cREnI82/DLHZbGF9o+r2QTO5UoYc9ZPytO1dyxkBasTgSpu46SyNfSdBPPUxpgm0XbLjXKk1tHqABEe830XmY6JDMzGHduLPSrfx8R/KxlnnvnZ9UBM2aOgDZ2we2bt2gP6FfyxxpSLDPRowpTKxKM+85CcJZxRNzHi743YmIGZPeCU7YA+xo9H3OsVMKbvWjLh++DZ2kiCNSfil7zK3WTLFwf3LziYsTHsjHkToisKEQPSJXeGqa/oGyG1Z2tvpAIWgbVlKqERpujzNQ7fMaUvHpqwwFR7aT1MTk6ocPNv3SngSlNezNffuXFJDifQOK5gyJmKEJsRBGoCSlXZKCeY8OmjbTJKjbnMzuBTN22l3rg1LikW3mC9QBbM1o1j9msUjuYN1pgDte3hD8d8msOIjjwRa9S8HT1p6rDfb2d09k8UhYVJwNTsXzAr5p7zgRLxJZ9a2D49cTi5/tWtTJJo5tbrmpFXeohc+TPCCbU9k1Trawpr+UbcvRgewKD9lXRXm2Z5ABj2u52bJKsUoN3CWN5JQr/FnnMZJ4NiJ7Nfdsb6GFxRblsi+zMejAsbObO3rekM7OshA/HCTcJaauWdNa8=
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: WfbpWI/7cpVp0tZB3xh2Ldaxxn20waE1K7X+370CKHjD2TnS9eAuhs50ydJY8UeUjdwuD7+cZ3UEP+SXh+lUlm1uZirPLfJZKvocLSPD7EtN+yf1qa+yVkATlmv9FtTypQ4S5SZ06ASXdIV8AfJRrsnvHwe6G0BoG3xC/ESEGBzSoa1VWyTAoxAIyH4vdpSgxVxf4G/IzKErdi/skVtSaoHcHYnkikzCkEtI+nd/AYPOcyKW0zOlHXx+NYQWkA4vxcxzEf72UCIXAW+Ksbw2ItE+fTBfeLU4BO0DiPuyuOjqFAXoNaKgo/jYorcxnKFT/4FRnaS1DJLXiZQo9LlwBFlA7prAZytUcEQ3HjNxfqXtSALNTlyW9c9P/mtWu8erCAdVgqKQBY8yIS4yCv3k5XUe/k9Z49AI0HT7hxBuWC6/USGEoCgfnrybkGJE0J5/QYItTDnnOQxSF2DoHjUkuL8+B3Rl3upa1gMGi5ceybP91nBBvFSRqODc0nzzLGVNncf/7W9CnOD0iaDg+bEMejRakWRB8I244Kg63FIEdeo1M6s+zAdlxV667IBCwcc1QEbxMZXVb9yI3MOzdowpK8l/okxnUAVcx3e8ox2pIaXs/TvmLmC5jksIdsHDlOY99rh4+FW733eDHpCJXzsz2kBybYS04LMy9XxxdmnUnBY=
  on:
    repo: FreeAllMedia/jsonapi-model-formatter
    branch: master
