language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
  - secure: SD7FzELjTop5BX+T9bqo/NGlGpCDd65kHlbGWGnAsbAEusR6SPyyeWl2heTzHabJYNd4sEM7GA5XL2GsQE7y1/ngYsJ60rhvhpBRotogeCxwdqO51kD/2Rp88HW5spaYIC9VVMm4GcKgtQtMNy5ww3u/RA5zc/jv0uBcRnYn8014VGVKLW1KIBFDYAEAocR8sxcFWEy0OTyhMJo+fU8mVlk7Od79l2xfMhijIz1SR909Pe0zRg1DchdfIcx9FBKK/OvaosydFAvhnxMUtHgWUf61NnS8DGVyvL60OZs7BO6Ug/cnMTw5KmLDXfQ5yY/G5LjaD/jKvgoc/zi3M3e1sjd1sSbYq+kLLg35dV7SPYsBmyMBRsvzpba8URnPuwCZjv6J4VRTW5ukXUF2S/kw/QT5u+X5cU/LQQv8hSIDia7aYmi4ztZDjlfJkRPJ6j0nLxShlg6gA1qggIchGrfsaM7c3lvHhv3mdo+mUfrNWoOhoQGFPN6GJhVyPu0r6M3UlO6y0xQUAXQZyd8Lz3mEAAfIXY0zpzk+08NDg1/ORBAzlSUkIWGtdHl4K8wb78M7HIBFHBhIYPc9Ii2jYNwxk9qCNzVMBLyZ9qBSaJWN8bqxyua4Z665qLGZS7sS6pQ96CjaVLZofxaumns0tE3RLEc5TLnsADlbOEASfFbxn1A=
  - secure: vT+XW+Nbn1jqOAMDPDF9FcxIi3Kf6PZLwg/KeSUI3jUG4+a9XP5X7MmEEIUa7XICPd5TSXr0UTOgrEIWOpvjE9Mu0OQVMISJUf9FXcbxPiCx9PZZMUaevDhEnfVbw0j876cS4D77nNKPLjdg0TLkgDq77ek4maDULmVKxP20+stXLDSM/FSOuCk92FOSA6u4T2VbPBh1e4QlDLn2+cvFEOXaEbjCyxqs94aM4TDLL7ARUq9jR0RTEXlRI8aQqaits2B93nSk+ic/RthnrR57AhDRd7x7al/ZRqbGa0zdBHinWJv1RuTsVsYS2dCWV/TToRVkd0EJhfo/3m11caId+ayUg/63CiGaM6VuEJXdjZuEaU9orcwm370TA5vnDAYgFziqo147nyxT8zIbxkyA9cIdg007kJLBVBNkehQ3VrGpXpiuQfGfUWG/H8u9LynCr+RHaIhUPJvU8X+TT5AbhM/kZInCaZVsaIH6s8+hGXYNUbOPszUMifYDABrsROTTLXq+XaYK70mox/6HUecwDUkbJ/F65gRI++MCs36pWUnXzqQnVkGOzyhB4wLf04B+KJSqmK3YZexqIjdLfctOaH8nSq8kPyD+p7ihc9gdWk+ocDSIUUoEjaZYoNhWn8wclHF9aXF3Y62CgsJidCc7P+GAqRd1mmhy4quEYk6/9OA=
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: qXsRneOIfNyWcxX/PsAXC3Z0hRdj0+cnzUiz4U8a1RuybH3mCorksrhyRoFCdZCEqHT3QWzqwv3RPdQgPx+5OH6b5dJuqNAXVO3G2vbx4vYbQ3iba0LQIweCmhHqSjyGVGfQMvJGPe4WKsK3jtYms8qnCfi3bmvEtM03S8I6je7JinJwPovYXsBbfW8rZ85EqUeg/xaNKV0jkMWnjYD1a+tS/aQGShxBtn0DAC9sjGF0LYv+TZ8o+hjjIDROA4k8mnDQ+/x3tkThRAyhaE2KFvVyD+ouBLE8dlHSWkb74l6f2RwDS2Ca/8WmUQxuPQ6nheJDXFAvxeTjXkdtc1jZFR4fSugSILFNZpT3wCfnDEjquwdoj1W/rRI2AIEvmoYe5AWf+IuWtqb4sPp9LqutDTU6fyMpSEvLkli4LCYAMGK7zt6YNyb9f4itAleBzBgng6viufbrMWTtRZ5COXKRveWW1G4bPslUw7uHkbMjkbcAO2Y7j05X+1psUQdl/nE1+0Mc5QxdfwzGnGk6KXKFAVq3Sg7f+1jfFptebxiOrEjJ3lUf+idDwcwX77QowpPM8dloMjGkFD735Lw7edWe3Yy/ECKYsRR1hRidauYv9BsNJKetul93VRzNXAYlEQlx2EDrOpeyyfL5neqH5zl0hdOX7/iaP4RQWM9KRU5qOCk=
  on:
    repo: FreeAllMedia/jsonapi-model-formatter
    branch: master
